cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash # Travis's default version is 1.3.2, we need 1.4.2 for nohoist
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install --global coveralls
install:
  - yarn install
language: node_js
node_js:
  - '10'
script:
  - yarn lint
  - yarn build
  - yarn test --coverage --coverageReporters=text-lcov | coveralls ; test ${PIPESTATUS[0]} -eq 0
  - yarn update-docs --scope=abi,light.js
